name: run main.py

on:
  schedule:
    - cron: '* * * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner
        with:
          ref: main

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python main.py
          
      - name: commit files
        run: |
          git config --local user.email "shopback.test.timchen@gmail.com"
          git config --local user.name "fuxtoyperson"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
